version: "3.8"

services:
  web:
    container_name: nextjs-dev
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules   # Avoid node_modules overwrite by host
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development